repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v12.0.1
    hooks:
    -   id: clang-format
        args: [-i, --style=Google]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
